name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: sonar-scanner
    # You may pin to the exact commit or the version.
    # uses: Warchant/setup-sonar-scanner@11711243d0cc6c260466862b5f7abd902f77b495
      uses: Warchant/setup-sonar-scanner@v3
      with:
        # Sonar-scanner version
        version: 4.2.0.1873
